#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo-white.png"
# use `x` with logo_width, example: "100x"
logo_width = "100x"
# logo text will only show when logo is missing.
logo_text = "Boilerplate"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "9567 Turner Trace Apt. BC C3G8A4"
mobile = "+211234565523"
email = "info@email.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = false
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

mainSections = ["blog"]
copyright = "Copyright &copy; 2021, All rights reserved. <br> Design & Develop by [GetHugoThemes](https://themefisher.com)"


[banner]
content = "Beautiful, Elegant and Vintage-inspired premium blog and portfolio theme."
bg_image= "images/banner.png"

[author_block]
title= "WELCOME TO MY BLOG"
image= "images/author.jpg"
content= "My name is Linda Smith. I am a writer, I like to travel and I love to photograph beautiful nature places and happy peoples."

[post_author]
title = "PUBLISHED BY JOHN WOOD"
avatar = "http://0.gravatar.com/avatar/f44e7d18176511aed07496128445e855?s=150&amp;d=mm&amp;r=g"
content = "I love traveling. Travel is my life, and not just the business that I do. This is part of me, part of my feelings, thoughts, my past and future, a source of new strength and inspiration. These are my friends, scattered all over the world, my favorite cities, favorite streets, houses, beaches, sunsets, snow, rains and everything from which the fabric of our life.."



[contact_form]
form_action = "xjvjeqde"
first_name = "First Name"
last_name = "Last Name"
email = "Your Email"
subject = "Subject"
message = "Leave a comment here"
submit = "send message"


# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.



# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"


############################# social site ########################
[[social]]
icon = "fab fa-facebook-f"
link = "#"

[[social]]
icon = "fab fa-twitter"
link = "#"

[[social]]
icon = "fab fa-instagram"
link = "#"

[[social]]
icon = "fab fa-dribbble"
link = "#"